### ISSUE TITLE
Touchscreen and setup.sh issue (manjaro)

### ISSUE THREAD

**Issue by BeatScherrer** [dmhacker/arch-linux-surface#85] opened 2019-12-28 17:14 UTC
I just installed the kernel (5.3.15-1)for my manjaro sb2 and the touchscreen is not working. I followed your steps to run the setup again after installing the kernel and only checked option 2. I rebooted and touchscreen is still not working. Weirdly in grub the touchscreen is working and I can select the boot partition with touchscreen.

Further information
after running your `setup.sh` again and accepting to overwrite the modules `/etc/mkinitcpio.conf` still lists `MODULES=""`.

I realized in the `setup.sh` execution gives the following logs:
```
==> Starting dry run: 5.3.15-1
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [autodetect]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
  -> Running build hook: [keyboard]
  -> Running build hook: [keymap]
  -> Running build hook: [resume]
  -> Running build hook: [filesystems]
==> Generating module dependencies
==> Dry run complete, use -g IMAGE to generate a real image
```
calling `mkinitcpio -g IMAGE` runs the command properly but I don't know what to do with the IMAGE currently. 

The modules are exracted correctly from `$cache_folder/$pathces_src_folder/root/etc/initramfs-tools/modules` and list
```
MODULES=(hid hid_sensor_hub i2c_hid hid_generic usbhid hid_multitouch intel_ipts surface_sam_ssh surface_sam_san surface_sam_vhf)
```
but
```
sed -i "/^MODULES=(.*)/c\\$modules" /etc/mkinitcpio.conf
```
is not replacing the modules in the mkinitcpio.conf file...
I use the following sed expression now to replace the `MODULES=` line:
```
sed -i -E "s|(^MODULES=).*|$modules|" /etc/mkinitcpio.conf
```

Will further try to make it work and update the comment.
Nevertheless Thank you for the work put into making the jakeday kernel work for arch systems.

**Comment by dmhacker** [comment] 2019-12-28 20:17
Can you try using the latest setup script and let me know if that fixes anything? I've modified the sed expression to be more inline with your version (replacing the change command with substitute and enabling enhanced regex).

**Comment by BeatScherrer** [comment] 2019-12-28 21:10
The `/etc/mkinitcpio.conf` file is edited and holds the following line:
```
MODULES=(hid hid_sensor_hub i2c_hid hid_generic usbhid hid_multitouch intel_ipts surface_sam_ssh surface_sam_san surface_sam_vhf)
```
(btw the `-i` option with sed can be extended to create a backup file with: `-i.backup` which is quite handy for sed commands.)

I have no real knowledge about the kernel and boot loading process but as far as I understand the initramfs holds the modules which are passed to the kernel by the bootloader. Since the touchscreen is working in the bootloader the initramfs is found but does not get loaded properly.

**Comment by dmhacker** [comment] 2019-12-28 22:50
That is expected behaviour. I updated the setup script to use -i.bak to create the backup file, so that should be good now. Is the touchscreen still not working?

**Comment by BeatScherrer** [comment] 2019-12-29 08:02
Touchscreen is now working after power cycling.

**Comment by dmhacker** [comment] 2019-12-31 19:53
Great! Since the touchscreen and setup script are working correctly, I'm going to close this issue.

**Comment by BeatScherrer** [comment] 2020-01-09 14:31
Hey Since KDE support is rather bad I decided to reinstall manjaro-gnome and just tested the script again. The modules can not be grepped and thus the following log is created:
```
sh setup.sh 
This script will prepare Surface devices for installation of a patched Arch Linux kernel.
Answer 'y' to any options you wish to install. By default, options are unselected.

Updating cache ...
Already up to date.
Already up to date.

1. Copy config files from qzed's kernel to root? [y/N] N

!!! WARNING !!! The following option will reset the MODULES option in your mkinitcpio config.
!!! WARNING !!! A backup of /etc/mkinitcpio.conf will be saved to /etc/mkinitcpio.conf.bak if you proceed.
2. Update /etc/mkinitcpio.conf using modules from initramfs-tools? [y/N] y
grep: .cache/linux-surface/root/etc/initramfs-tools/modules: No such file or directory
MODULES=() will be added to /etc/mkinitcpio.conf.
==> Starting dry run: 5.4.6-1-surface
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [autodetect]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
  -> Running build hook: [keyboard]
  -> Running build hook: [keymap]
  -> Running build hook: [resume]
  -> Running build hook: [filesystems]
==> Generating module dependencies
==> Dry run complete, use -g IMAGE to generate a real image
Done fixing mkinitcpio.conf.
```

**Comment by dmhacker** [comment] 2020-01-09 17:03
@BeatScherrer

**Closed** 2020-01-09 17:06 UTC
Labels: bug, manjaro, touchscreen
