### ISSUE TITLE
[Surface Laptop 2] Touchscreen not working after updated to 5.3.10-1

### ISSUE THREAD

**Issue by hywhuangyuwei** [dmhacker/arch-linux-surface#79] opened 2019-11-29 15:03 UTC
Touchscreen was working perfectly on kernel 5.1.15-1, but after the update the touchscreen stops working. I try to fix this by re-run `sudo sh setup.sh` and select yes for all options but failed.

**Comment by k0pernicus** [comment] 2019-11-30 10:59
Hi,
Can you explain what failed with the execution of `setup.sh` please?
Is it the script, or the script was ok but touchscreen still not working?
Also, are you running 5.3.10-1 kernel version with surface support (`uname -a`)?

**Comment by hywhuangyuwei** [comment] 2019-11-30 11:06
Actually the script run returns 0 but touchscreen still not working.
Also `uname -r` outputs `5.3.10-1`

**Comment by agaleski** [comment] 2019-12-05 10:28
I fixed this problem for kernel 5.3 today on my Surface Laptop (1) [This one uses MSHW0079].
Two problems:
* /etc/mkinitcpio.conf did not include the intel-ipts module. I had to add it like `MODULES="intel-ipts"` + then run `sudo mkinitcpio -g /boot/initramfs-linux-surface.img` and finally reboot
* now it turned out there was no folder /usr/lib/firmware/intel/ipts/MSHW0079 ... the MSHW0079 needed for my Surface Laptop was missing. I had to download a fixed version from here: https://github.com/qzed/linux-surface/tree/master/firmware/intel/ipts/MSHW0079

After a final reboot it works perfectly for now. :+1:

**Comment by hywhuangyuwei** [comment] 2019-12-05 10:43
> I fixed this problem for kernel 5.3 today on my Surface Laptop (1) [This one uses MSHW0079].
> Two problems:
> 
> * /etc/mkinitcpio.conf did not include the intel-ipts module. I had to add it like `MODULES="intel-ipts"` + then run `sudo mkinitcpio -g /boot/initramfs-linux-surface.img` and finally reboot
> * now it turned out there was no folder /usr/lib/firmware/intel/ipts/MSHW0079 ... the MSHW0079 needed for my Surface Laptop was missing. I had to download a fixed version from here: https://github.com/qzed/linux-surface/tree/master/firmware/intel/ipts/MSHW0079
> 
> After a final reboot it works perfectly for now. 👍

Thanks. I will try it out. Hope this proplem can be fixed ASAP. 😁 @dmhacker

**Comment by agaleski** [comment] 2019-12-05 11:30
please note:

use `dmesg` command after step one to identify which MSHW version you need for your surface laptop 2 ;)

**Comment by qzed** [comment] 2019-12-09 12:37
As a note: We've changed the way the firmware is loaded. The old paths (/lib/firmware/intel/ipts/...) have been changed to (/lib/firmware/intel/ipts/<model>/...). This new path should now be preferred, although as a fallback, the firmware will still be loaded from the old paths if it can't be found in the new ones.

This specific issue is however likely caused by some other updates in the IPTS driver. The original firmware for the laptops (MSHW0079, both SL1 and SL2) contains a HID descriptor that Linux had some problems with. In Jake's version of the kernel/patches, he patched the Linux HID driver to fix that. We've now decided to fix the problem in the firmware itself so, so that we don't have to modify the kernel and push for upstream changes. So you will need to update the MSHW0079 firmware with the one found in https://github.com/qzed/linux-surface/tree/master/firmware/intel/ipts. (More info on this: https://github.com/qzed/linux-surface-kernel/wiki/IPTS-Firmware#bogus-hid-descriptor-for-surface-laptops-mshw0079).

**Comment by Demonstrandum** [comment] 2019-12-19 15:50
@agaleski that worked perfectly thank you!  the `MSHW0137` folder for the Surface Book 2 was missing, downloading it and placing it in the `/usr/lib/firmware/intel/ipts/` folder solved it.

**Comment by dmhacker** [comment] 2019-12-27 23:47
See commit 2b8565c.

All firmware is now copied properly to /lib/firmware (and /usr/lib/firmware by extension since the two are hard-linked) regardless of device models. This will set up paths in line with what qzed was talking about. 

Closing this issue since it is no longer a problem.

**Closed by dmhacker** 2019-12-27 23:47 UTC
Labels: touchscreen
