### ISSUE TITLE
SP4 does not Wake from Hibernation

### ISSUE THREAD

**Issue by k4ever** [dmhacker/arch-linux-surface#19] opened 2019-02-03 13:58 UTC
I can't get my SP4 to wake from hibernation. The keyboard lights up, but the screen never comes on. I eventually have to reboot to get the system back. 

I'm running the latest 4.19.19-1 kernel in Manjaro KDE on my 8GB Core i5 SP4. I have an 8GB swap partition set up and resume=UUID=swap partition's UUID is set in GRUB by the installer. I also answered yes to replace suspend with hibernation during the setup.sh file.

**Comment by dmhacker** [comment] 2019-03-12 18:03
Yeah, I am experiencing a similar issue. The issue is that, with jakeday's kernel, I believe the hibernation feature doesn't play well with the IPTS touch-screen. You will have  to disable the touch-screen in order to get some semblance of hibernation working. See issues on jakeday's repository for more information.

**Comment by dmhacker** [comment] 2019-09-04 21:31
Closing because this is a known issue that is related to the content of jakeday's patches and not to the process through which the patches are applied.

**Closed by dmhacker** 2019-09-04 21:31 UTC
Labels: upstream bug
