### ISSUE TITLE
Modules not found. Cannot install patched kernel.

### ISSUE THREAD

**Issue by dantesch** [dmhacker/arch-linux-surface#77] opened 2019-11-25 00:00 UTC
I am using a Surface Laptop 2, dual booted with Windows 10.

When running `sudo sh setup.sh` I say yes to copying files to root, then yes to rebuild kernel with modules from `/etc/initramfs-tools/modules` and get the following errors:

> ==> ERROR: module not found: 'intel_ipts'
> ==> ERROR: module not found: 'surface_acpi'

I then continue through `setup.sh`, saying yes to all and all seems fine after.

I have then tried to compile and install my own kernel, and install from the releases tab.
Both have errors saying:

> ==> ERROR: module not found: 'surface_acpi'
...
> WARNING: Possibly missing firmware for module: wd719x
> WARNING: Possibly missing firmware for module: aic94xx
...
> ==> Creating gzip-compressed initcpio image: /boot/initramfs-linux-surface-fallback.img
> == WARNING: errors were encountered during the build. The image may not be complete.
> error: command failed to execute correctly

**Comment by todworgen** [comment] 2019-11-28 17:55
Same for me, because of the missing surface_acpi you just cant install the rest of the kernel..

**Comment by skogsmaskin** [comment] 2019-11-28 21:53
There is an issue for this already: https://github.com/dmhacker/arch-linux-surface/issues/73#issuecomment-557926389

**Comment by todworgen** [comment] 2019-11-29 01:00
So we are stuck until this issue is resolved? Because when I try to install the gen5 acpi module from qzed I get some weird error because it wants things that dont exist when I clone it of git...

maybe you got some idea how we can get a new surface_acpi

**Comment by PandorasFox** [comment] 2019-12-07 19:42
the surface_acpi module was replaced by a few surface_sam modules. If you try again from the latest stuff in qzed's repo this should work now.

**Comment by dmhacker** [comment] 2019-12-10 05:14
Closing this issue because it's a duplicate of #73. Use qzed's repo for now; I will get to fixing this after I finish finals.

**Closed by dmhacker** 2019-12-10 05:14 UTC
